config/routes.rb
Ishportfolio::Engine.routes.draw do
  resources :categories
  resources :items
  get '/', :to => 'items#index'
end

app/models/ishportfolio/category.rb
module Ishportfolio
  class Category < ActiveRecord::Base
  	# This assumes you already have friendly_id in your gemfile and all that good stuff.
  	extend FriendlyId
  	friendly_id :slug, use: :slugged

    # Uploader
    mount_uploader :image, ImageUploader

  	# Association
  	has_and_belongs_to_many :items

  	# Fields validation
  	SLUG_REGEX = /\A^[\w&-]+$\Z/

  	validates :title, presence: true,
  	            length: { maximum: 250 }

  	validates :slug, presence: true,
  	            length: { maximum: 250 },
  	            format: SLUG_REGEX
  end
end

app/models/ishportfolio/item.rb
module Ishportfolio
  class Item < ActiveRecord::Base
  	# Association
  	has_and_belongs_to_many :categories

  	# Uploader
	mount_uploader :image, ImageUploader

  	# Validation
  	validates :title, presence: true,
  	            length: { maximum: 250 }
  end
end

app/controllers/ishportfolio/application_controller.rb
module Ishportfolio
  class ApplicationController < ::ApplicationController
  	
  end
end

app/controllers/ishportfolio/categories_controller.rb
require_dependency "ishportfolio/application_controller"

module Ishportfolio
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    layout 'application'

    # GET /categories
    def index
      @categories = Category.all
    end

    # GET /categories/1
    def show
      @items = @category.items.page(params[:page])
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.friendly.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:title, :slug, :content, :image)
      end
  end
end

app/controllers/ishportfolio/items_controller.rb
require_dependency "ishportfolio/application_controller"

module Ishportfolio
  class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    layout 'application'

    # GET /items
    def index
      @items = Item.page(params[:page])
      @categories = Category.all
    end

    # GET /items/1
    def show
      @categories = @item.categories.all
    end

    # GET /items/new
    def new
      @item = Item.new
      @categories = Category.all
    end

    # GET /items/1/edit
    def edit
      @categories = Category.all
    end

    # POST /items
    def create
      @item = Item.new(item_params)

      if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /items/1
    def update
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /items/1
    def destroy
      @item.destroy
      redirect_to items_url, notice: 'Item was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_item
        @item = Item.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def item_params
        params.require(:item).permit(:title, :content, :image, { :category_ids => [] })
      end
  end
end

app/helpers/ishportfolio/application_helper.rb
module Ishportfolio
  module ApplicationHelper
  	# Generates entity cover image
  	def load_ishportfolio_image(entity, size={})
  		size = size ||= :medium
  		if !entity.image_url.blank?
  			image_tag( entity.image_url(size).to_s, { :class => 'img-responsive', :alt => entity.title, :title => entity.title })
  		end
  	end

  	# Generates entity excerpt
	def load_ishportfolio_excerpt(entity, length=100)
		truncate(strip_tags(entity.content).html_safe, :length => length, :escape => false)
	end
  end
end

app/helpers/ishportfolio/categories_helper.rb
module Ishportfolio
  module CategoriesHelper
  end
end

app/helpers/ishportfolio/items_helper.rb
module Ishportfolio
  module ItemsHelper
  end
end

app/views/ishportfolio/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <div class="col-md-8">

      <div class="field form-group">
        <%= f.label :title %>
        <%= f.text_field :title, { :required => true, :id => 'title', :class => 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :slug %>
        <%= f.text_field :slug, { :required => true, :id => 'slug', :class => 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :content %>
        <%= f.text_area :content, { :id => 'content', :class => 'form-control', :rows => 10 } %>
      </div>
      <div class="actions form-group">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>

    </div>
    <div class="col-md-4">

      <% if !@category.image.blank? %>
        <p class="text-center">
          <%= load_ishportfolio_image @category, :medium %>
        </p>
      <% end %>

      <div class="field form-group">
        <%= f.label :image %>
        <%= f.file_field :image, :class => 'btn btn-block btn-default', :accept => 'image/png,image/gif,image/jpeg,image/jpg' %>

        <p class="help-block"><%= t('ishportfolio.max_image_size') %><br />
        <%= t('ishportfolio.allowed_image_formats') %> </p>
      </div>

    </div>
  </div>


  
<% end %>

app/views/ishportfolio/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/ishportfolio/categories/index.html.erb
<% content_for :header do %>
  <h1>Portfolio Categories</h1>
<% end %>

<% if can? :create, Ishportfolio::Category %>
  <div class="clearfix">
    <p class="pull-right">
      <%= link_to 'New Category', new_category_path, :class => 'btn btn-primary' %>
    </p>
  </div>
<% end %>

<% @categories.each do |category| %>
  <div class="clearfix">
    <div class="col-md-3">
      <%= link_to load_ishportfolio_image(category, :thumb), category %>
    </div>
    <div class="col-md-9">
      <h2><%= link_to category.title, category %></h2>
      <%= load_ishportfolio_excerpt category, 300 %>
      <div class="clearfix">
        <p class="pull-right">
          <% if can? :update, category %>
            <%= link_to 'Edit', edit_category_path(category) %> | 
          <% end %>
          <% if can? :destroy, category %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/ishportfolio/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/ishportfolio/categories/show.html.erb
<% content_for :header do %>
  <h1><%= @category.title %></h1>
<% end %>

<div class="well clearfix">
  <% if !@category.image.blank? %>
    <div class="col-md-3">
      <p><%= load_ishportfolio_image @category, :thumb %></p>
    </div>
    <div class="col-md-9">
      <%= @category.content.html_safe %>
      <div class="clearfix">
        <p class="pull-right">
        	<%= link_to 'Edit', edit_category_path(@category), :class => 'btn btn-warning' %>
        	<%= link_to 'Destroy', @category, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
  <% end %>
</div>

<%=  render :partial => 'ishportfolio/items/load_all_items', :locals => { :items => @items } %>

app/views/ishportfolio/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <div class="col-md-8">
      
      <div class="field form-group">
        <%= f.label :title %>
        <%= f.text_field :title, { :required => true, :id => 'title', :class => 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :content %>
        <%= f.text_area :content, { :required => true, :id => 'content', :class => 'form-control', :rows => 10 } %>
      </div>
      <div class="actions form-group">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>

    </div>
    <div class="col-md-4">
      <div class="field form-group form-upload">

        <% if !@item.image.blank? %>
          <p><%= load_ishportfolio_image @item, :medium %></p>
        <% else %>
          <%= f.label :image %>
        <% end %>
        <%= f.file_field :image, :class => 'btn btn-block btn-default', :accept => 'image/png,image/gif,image/jpeg,image/jpg' %>
        <p class="help-block"><%= t('ishportfolio.max_image_size') %><br />
        <%= t('ishportfolio.allowed_image_formats') %> </p>

      </div>

      <div class="field form-group well">
        <%= f.label :categories %><br />
        <% @categories.all.each do |category| %>
          <%= check_box_tag 'item[category_ids][]', category.id, @item.category_ids.include?(category.id) %>
          <%= category.title %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/ishportfolio/items/_load_all_items.html.erb
<div class="clearfix portfolio-items">
  <% if !items.blank? %>
    <% items.each do |item| %>
        <div class="col-md-4 item">
          <div class="content">
            <h3 class="text-center title"><%= link_to item.title, ishportfolio.item_path(item), :title => item.title %></h3>
            
            <p class="text-center thumbnail">
              <%= link_to load_ishportfolio_image(item, :medium), ishportfolio.item_path(item), :title => item.title %>
            </p>
            
            <p class="text-center">
              <% if can? :update, item %>
                <%= link_to 'Edit', ishportfolio.edit_item_path(item), :class => 'btn btn-xs btn-warning' %>
              <% end %>
              <% if can? :destroy, item %>
                <%= link_to 'Destroy', ishportfolio.item_path(item), :class => 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </p>
          </div>
        </div>
    <% end %>
  <% else %>
    <p class="lead text-center"><%= t('ishportfolio.items.no_item') %></p>
    <% if can? :create, Ishportfolio::Item %>
      <p class="text-center">
        <%= link_to 'New Item', ishportfolio.new_item_path, :class => 'btn btn-primary' %>
      </p>
    <% end %>
  <% end %>
  
</div>

app/views/ishportfolio/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/ishportfolio/items/index.html.erb
<% content_for :header do %>
	<h1>Portfolio</h1>
<% end %>

<% if can? :create, Ishportfolio::Item %>
  <div class="clearfix">
    <p class="pull-right">
      <%= link_to 'New Item', new_item_path, :class => 'btn btn-primary' %>
    </p>
  </div>
<% end %>

<%= render :partial => 'load_all_items', :locals => { :items => @items } %>

<div class="clearfix">
  <%= paginate @items %>
</div>

app/views/ishportfolio/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/ishportfolio/items/show.html.erb
<% content_for :header do %>
  <h1>Portfolio: Project "<%= @item.title %>"</h1>
<% end %>

<div class="portfolio-item-show">
	<p class="text-center thumbnail">
		<%= load_ishportfolio_image @item, :medium %>
	</p>

	<h1 class="text-center"><%= @item.title %></h1>
	<% if !@categories.blank? %>
		<p class="text-muted text-center">
			Type:
			
				<% @categories.each do |category| %>
					<%= link_to "#{category.title} | ", category %>
				<% end %>
			
		</p>
	<% end %>

	<div class="clearfix">
		<%= @item.content.html_safe %>
	</div>

	<div class="clearfix">
		<p class="pull-right">
			<% if can? :update, @item %>
				<%= link_to 'Edit', edit_item_path(@item), :class => 'btn btn-warning' %>
			<% end %>
			<% if can? :destroy, @item %>
				<%= link_to 'Destroy', @item, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</p>
	</div>
</div>

app/views/layouts/ishportfolio/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ishportfolio</title>
  <%= stylesheet_link_tag    "ishportfolio/application", media: "all" %>
  <%= javascript_include_tag "ishportfolio/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>